version: '3'
services:
  app:
    image: node:carbon-alpine
    command: node app/index.js
    volumes:
      - .:/home/app
    working_dir: /home/app
    ports:
      - 3000:3000
  rabbitmq:
    image: rabbitmq:3.7-alpine
